language: go


go: "1.13.x"
env:
  global
  - GO111MODULE=on

script:
  - go test -v ./... -covermode=count -coverprofile=coverage.out
  - $GOPATH/bin/goveralls -service=travis-ci -coverprofile=coverage.out -repotoken=$COVERALLS_TOKEN
  #- golangci-lint run ./...


install: true

sudo: required

before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin v1.23.1

before_install:
  - go get golang.org/x/lint/golint
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls


